import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";

export interface ExportPdfConfig {
  title: string;
  columns: string[];
  data: (string | number)[][];
  filename?: string;
  orgName?: string;
  orgLogo?: string; // Optional logo URL
  orgAddress?: string; // Optional formatted address line
}

export async function exportToPdf({
  title,
  columns,
  data,
  filename,
  orgName,
  orgLogo,
  orgAddress,
}: ExportPdfConfig) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42); // slate-900

  let startY = 46;

  if (orgLogo) {
    try {
      // Create an image element to load the logo
      const img = new Image();
      img.crossOrigin = "Anonymous"; // Try to avoid CORS issues if fetching from Clerk/Uploadthing
      img.src = orgLogo;

      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });

      // Maintain aspect ratio. Height is capped at 16px to fit nicely.
      const ratio = img.width / img.height;
      const height = 16;
      const width = height * ratio;

      // Calculate center position for both logo and text
      const nameWidth =
        (doc.getStringUnitWidth(orgName || "SwiftStock") * 22) /
        doc.internal.scaleFactor;
      const totalWidth = width + 4 + nameWidth; // 4px spacing between logo and text
      const startX = (pageWidth - totalWidth) / 2;

      // Add image at calculated center layout
      doc.addImage(img, "PNG", startX, 10, width, height);

      // Draw text next to logo
      doc.text(orgName || "SwiftStock", startX + width + 4, 22.5, {
        align: "left",
      });
    } catch (e) {
      console.error("Failed to load PDF logo:", e);
      // Fallback gracefully to text-only
      doc.text(orgName || "SwiftStock", pageWidth / 2, 20, { align: "center" });
    }
  } else {
    doc.text(orgName || "SwiftStock", pageWidth / 2, 20, { align: "center" });
  }

  // Draw optional address below the main org name
  if (orgAddress) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(orgAddress, pageWidth / 2, 28, { align: "center" });
    startY += 8; // Push table down to accommodate address
  }

  // Divider Line
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, startY - 18, pageWidth - 14, startY - 18);

  // Report Title & Metadata
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59); // slate-800
  doc.text(title, 14, startY - 10);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(`Generated on: ${format(new Date(), "PPpp")}`, 14, startY - 4);

  autoTable(doc, {
    startY: startY + 2,
    head: [columns],
    body: data,
    theme: "grid",
    styles: {
      fontSize: 8.5,
      cellPadding: 5,
      font: "helvetica",
      textColor: [51, 65, 85], // slate-700
      lineColor: [226, 232, 240], // slate-200
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: [248, 250, 252], // slate-50
      textColor: [71, 85, 105], // slate-600
      halign: "left",
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255], // white
    },
    bodyStyles: {
      fillColor: [255, 255, 255],
    },
  });

  // Summary stats below the table
  const finalY = (doc as any).lastAutoTable?.finalY || startY + 20;
  if (data.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(`Total Items: ${data.length}`, 14, finalY + 8);
    doc.text(`Report generated by SwiftStock`, pageWidth - 14, finalY + 8, {
      align: "right",
    });
  }

  const pageCount = (doc as any).internal.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: "right" },
    );
  }

  const safeTitle = title.replace(/\s+/g, "_").toLowerCase();
  const dateStr = format(new Date(), "yyyy-MM-dd");
  doc.save(filename || `${safeTitle}_${dateStr}.pdf`);
}
